server.port=8081
spring.application.name=petstore-lite
spring.datasource.url=jdbc:postgresql://localhost:5432/petstore
spring.datasource.username=petadmin
spring.datasource.password=s3cret
logging.level.root=INFO
