//! `rustjvm-docs` — generates API documentation from RustJVM metadata.
//!
//! Two outputs:
//!   - [`generate_openapi`]: an OpenAPI 3 document (JSON) covering every
//!     route the compiler discovered, with query parameters and responses.
//!   - [`generate_bean_graph`]: a markdown dependency graph of the DI
//!     container — every bean, its kind/scope, and what it injects.

use rustjvm_compiler::{BeanSpec, CompiledRoute};

/// OpenAPI 3.0 JSON for the given routes.
pub fn generate_openapi(title: &str, routes: &[CompiledRoute]) -> String {
    let mut paths = serde_json::Map::new();
    for route in routes {
        let parameters: Vec<serde_json::Value> = route
            .params
            .iter()
            .map(|p| {
                serde_json::json!({
                    "name": p.query_key,
                    "in": "query",
                    "required": p.required,
                    "schema": { "type": "string" },
                })
            })
            .collect();

        let op = serde_json::json!({
            "operationId": format!("{}.{}", route.class_name, route.method_name),
            "summary": format!("{}.{}", route.class_name, route.method_name),
            "parameters": parameters,
            "responses": {
                "200": {
                    "description": "OK",
                    "content": { "text/plain": { "schema": { "type": "string" } } },
                },
                "400": { "description": "Missing or invalid query parameter" },
                "501": { "description": "Method body outside the compiler subset" },
            },
            "x-rustjvm": {
                "class": route.class_name,
                "method": route.method_name,
            },
        });

        paths
            .entry(route.path.clone())
            .or_insert_with(|| serde_json::Map::new().into())
            .as_object_mut()
            .expect("path item object")
            .insert(route.http_method.to_lowercase(), op);
    }

    let doc = serde_json::json!({
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": "0.1.0",
            "description": "Generated by rustjvm docs from RustJVM compiler metadata.",
        },
        "paths": paths,
    });
    serde_json::to_string_pretty(&doc).expect("openapi doc serializes")
}

/// Markdown bean dependency graph.
pub fn generate_bean_graph(beans: &[BeanSpec]) -> String {
    let mut out = String::from("# Bean Dependency Graph\n\n");
    out.push_str("| Bean | Type | Kind | Scope | Injects |\n");
    out.push_str("|------|------|------|-------|---------|\n");
    let mut sorted: Vec<&BeanSpec> = beans.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for b in &sorted {
        let deps = if b.dependencies.is_empty() {
            "—".to_string()
        } else {
            b.dependencies
                .iter()
                .map(|d| format!("`{}` ({})", d.field_name, d.type_name))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | {:?} | {:?} | {} |\n",
            b.name, b.class_name, b.kind, b.scope, deps
        ));
    }

    out.push_str("\n## Edges\n\n```\n");
    for b in &sorted {
        for d in &b.dependencies {
            out.push_str(&format!("{} --{}--> {}\n", b.name, d.field_name, d.type_name));
        }
    }
    out.push_str("```\n");
    out
}
